development:
    dialect: sqlite3
    datasource: ../oaf.db
    dir: sqlite
    table: migrations

production:
    dialect: postgres
    datasource: dbname=ofa-server sslmode=disable
    dir: postgres
    table: migrations