development:
    dialect: sqlite3
    datasource: ../oaf.db
    dir: sqlite
    table: migrations

production:
    dialect: postgres
    datasource: dbname=oaf-server user=oaf-server password=oaf-server sslmode=disable
    dir: postgres
    table: migrations