output   = "../../../internal/db/psqlmodel"
wipe     = true
no-tests = true
pkgname  = "psqlmodel"

[psql]
  dbname = "oaf-server"
  host   = "localhost"
  port   = 5432
  user   = "oaf-server"
  pass   = "oaf-server"
  blacklist = ["migrations"]
  sslmode = "disable"