-- +migrate Up
--
-- File generated with SQLiteStudio v3.2.1 on Di Okt 13 09:16:59 2020
--
-- Text encoding used: System
--

-- Table: Attendees
CREATE TABLE Attendees (
	EventID INTEGER REFERENCES Events (EventID) ON DELETE CASCADE ON UPDATE CASCADE, 
	UserID INTEGER REFERENCES Users (UserID) ON DELETE CASCADE ON UPDATE CASCADE, 
	Commitment INTEGER NOT NULL, 
	Comment TEXT, 
	PRIMARY KEY (EventID, UserID)
);

-- Table: Comments
CREATE TABLE Comments (
	CommentID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 
	EventID INTEGER REFERENCES Events (EventID) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL, 
	UserID INTEGER REFERENCES Users (UserID) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL, 
	Comment TEXT NOT NULL
);

-- Table: Events
CREATE TABLE Events (
	EventID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 
	OrganizationID INTEGER REFERENCES Organizations (OrganizationID) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL, 
	Name TEXT NOT NULL, 
	Address TEXT, 
	Start TIME NOT NULL, 
	"End" TIME, 
	Creator INTEGER REFERENCES Users (UserID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Table: Members
CREATE TABLE Members (
	SectionID INTEGER REFERENCES Sections (SectionID) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL, 
	UserID INTEGER REFERENCES Users (UserID) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL, 
	Rights INTEGER NOT NULL, 
	PRIMARY KEY (SectionID, UserID)
);

-- Table: Organizations
CREATE TABLE Organizations (
	OrganizationID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 
	Name TEXT NOT NULL, 
	Picture BLOB
);

-- Table: Sections
CREATE TABLE Sections (
	SectionID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 
	OrganizationID INTEGER REFERENCES Organizations (OrganizationID) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL, 
	Name TEXT NOT NULL
);

-- Table: Users
CREATE TABLE Users (
	UserID INTEGER PRIMARY KEY AUTOINCREMENT, 
	Username TEXT NOT NULL, 
	Password TEXT NOT NULL, 
	Showname TEXT, 
	EMail TEXT NOT NULL, 
	SuperUser BOOLEAN NOT NULL
);

-- Table: Info
CREATE TABLE Info (
	"Key" TEXT PRIMARY KEY,
	"Value" TEXT
);

-- +migrate Down
DROP TABLE "Organizations";
DROP TABLE "Users";
DROP TABLE "Members";
DROP TABLE "Events";
DROP TABLE "Attendees";
DROP TABLE "Comments";
DROP TABLE "Section";